// Generated by sync_luma.py from the UCLAISI Luma calendar. Don't edit by hand:
// run `python3 sync_luma.py` to refresh. Last synced 2026-09-30 01:31 UTC.
const LUMA_EVENTS = [
  {"title": "Deepmind x Reuters speakers and networking", "start": "2026-10-08T17:00:00Z", "end": "2026-10-08T18:00:00Z", "url": "https://luma.com/8pyem4nv"},
];
