#!/usr/bin/env python3
"""Copy upcoming events from the UCLAISI Luma calendar into events.js.

Luma doesn't let browsers read its calendars from other websites, so the page can't fetch
events live. This script downloads the calendar's public .ics feed and writes a snapshot
the site loads. serve.sh runs it on start; run it by hand (or on a schedule where the site
is hosted) to refresh:

    python3 sync_luma.py

If Luma can't be reached, the existing events.js is left as it is.
"""

import datetime as dt
import json
import pathlib
import re
import subprocess
import sys
import urllib.error
import urllib.request
from zoneinfo import ZoneInfo

CALENDAR_ID = "cal-EPIpUE43y4I3i7H"  # lu.ma/UCLAISI
ICS_URL = f"https://api.lu.ma/ics/get?entity=calendar&id={CALENDAR_ID}"
LOCAL_TZ = ZoneInfo("Europe/London")
OUT = pathlib.Path(__file__).with_name("events.js")


def fetch_ics():
    req = urllib.request.Request(ICS_URL, headers={"User-Agent": "uclaisi-site-sync"})
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            return resp.read().decode("utf-8")
    except urllib.error.URLError as err:
        if "CERTIFICATE_VERIFY_FAILED" not in str(err):
            raise
        # Some Python installs (e.g. python.org on macOS) ship without root certificates.
        # The system curl uses the OS certificate store, so try that instead.
        result = subprocess.run(["curl", "-sfL", "--max-time", "20", ICS_URL], capture_output=True, check=True)
        return result.stdout.decode("utf-8")


def unescape(value):
    return re.sub(r"\\([\\,;nN])", lambda m: "\n" if m.group(1) in "nN" else m.group(1), value)


def parse_time(params, value):
    if value.endswith("Z"):
        return dt.datetime.strptime(value, "%Y%m%dT%H%M%SZ").replace(tzinfo=dt.timezone.utc)
    if len(value) == 8:  # all-day event
        return dt.datetime.strptime(value, "%Y%m%d").replace(tzinfo=LOCAL_TZ)
    tz = ZoneInfo(params["TZID"]) if "TZID" in params else LOCAL_TZ
    return dt.datetime.strptime(value, "%Y%m%dT%H%M%S").replace(tzinfo=tz)


def parse_events(ics):
    lines = re.sub(r"\r?\n[ \t]", "", ics).splitlines()  # unfold wrapped lines
    events, current = [], None
    for line in lines:
        if line == "BEGIN:VEVENT":
            current = {}
        elif line == "END:VEVENT":
            events.append(current)
            current = None
        elif current is not None and ":" in line:
            head, value = line.split(":", 1)
            name, *rest = head.split(";")
            params = dict(p.split("=", 1) for p in rest if "=" in p)
            current[name] = (params, value)
    return events


def to_site_event(ev):
    if ev.get("STATUS", ({}, ""))[1] == "CANCELLED":
        return None
    start = parse_time(*ev["DTSTART"])
    end = parse_time(*ev["DTEND"]) if "DTEND" in ev else start
    description = unescape(ev.get("DESCRIPTION", ({}, ""))[1])
    link = re.search(r"https://(?:lu\.ma|luma\.com)/\S+", description)
    location = ev.get("LOCATION", ({}, ""))[1]
    return {
        "title": unescape(ev["SUMMARY"][1]).strip(),
        "start": start.astimezone(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "end": end.astimezone(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "url": link.group(0) if link else (location if location.startswith("http") else "https://lu.ma/UCLAISI"),
    }


def main():
    try:
        ics = fetch_ics()
    except Exception as err:  # offline, Luma down, etc.
        print(f"Luma sync failed ({err}). Keeping the existing events.js.", file=sys.stderr)
        return 1

    now = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    events = [e for e in map(to_site_event, parse_events(ics)) if e and e["end"] > now]
    events.sort(key=lambda e: e["start"])

    synced = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    body = "".join(f"  {json.dumps(e, ensure_ascii=False)},\n" for e in events)
    OUT.write_text(
        "// Generated by sync_luma.py from the UCLAISI Luma calendar. Don't edit by hand:\n"
        f"// run `python3 sync_luma.py` to refresh. Last synced {synced}.\n"
        f"const LUMA_EVENTS = [\n{body}];\n",
        encoding="utf-8",
    )
    print(f"Synced {len(events)} upcoming event{'s' if len(events) != 1 else ''} from Luma into {OUT.name}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
